### ISSUE TITLE
Priority on conditional arguments for cmake

### ISSUE THREAD

**Issue by MarcoRuzzon** [ADVRHumanoids/forest#17]
In the example recipe below, the flag DBUILD_TOOLS appears both for standard compilation and for *xeno* mode compilation. In case of conflicts like this I think flags specified under *args_if* should be the ones used to compile the project. 

NOTE: I think that cmake uses the first flag and does not take into account any repetitions.

```yaml
clone:
  type: git
  server: gitlab.advr.iit.it
  repository: xeno-ecat/ecat_master_advr.git
  tag: xbot2_fixed

build:
  type: cmake
  args:
    - -DBUILD_TOOLS=OFF
    - -DCMAKE_BUILD_TYPE=Release
  args_if:
    xeno:
      - -DCMAKE_USE_XENOMAI=ON
      - -DENABLE_XENO=ON
      - -DBUILD_TOOLS=ON

depends:
  - soem
  - cppzmq
  - ZeroMQ
  - cap2-bin
  - protobuf
  - yaml-cpp
  - Eigen3
```
