### ISSUE TITLE
Foresst should not prompt for pwd when recipe's custom fetch and build sections contains sudo cmds if if --pwd flag is used

### ISSUE THREAD

**Issue by MarcoRuzzon** [ADVRHumanoids/forest#18]
Example:
- command: 
```sh
$ forest xbot_env  --pwd
```

- xbot_env recipe:
```yml
clone:
  type: custom
  cmd:
    - sudo sh -c 'echo "deb http://xbot.cloud/xbot2/ubuntu/$(lsb_release -sc) /" > /etc/apt/sources.list.d/xbot-latest.list'
    - wget -q -O - http://xbot.cloud/xbot2/ubuntu/KEY.gpg | sudo apt-key add -
    - sudo apt update

build:
  type: custom
  cmd:
    - sudo apt install xbot_env

depends: []
```

This should be true starting from 2bf1028a18e3440a50a9de0cc1bdd0b8c6983180
