### ISSUE TITLE
Skip history option for git clone facility

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/forest#20]
Goal: `forest my_pkg --git-skip-history` clones `my_pkg` with `git clone --branch <tag> --depth 1 git@etcetcetc` in order to save bandwidth. 

This is critical especially with some broken repos such as Xenomai, where the history is crazy large.

For now, we can use this workaround:
```
clone:
  type: custom
  cmd:
    - git clone --branch v3.1_cmake --depth 1 git@gitlab.advr.iit.it:amargan/xenomai.git
    - cp -r xenomai/* {srcdir}
```

@liesrock
