### ISSUE TITLE
Build type override

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/forest#5]
Should be possible to override the build type from a recipe, e.g.
```yaml
build:
  type: cmake
  args: 
    - -DDCMAKE_BUILD_TYPE=""
```
