### ISSUE TITLE
Conditional cmake args 

### ISSUE THREAD

**Issue by alaurenzi** [ADVRHumanoids/forest#8]
Latest devel now supports (maybe) conditional cmake args. 

The first draft is very simple. Given a recipe such as
```yaml
clone:
  type: git
  server: github.com
  repository: advrhumanoids/xbot2_examples.git
  tag: fi_gripper_btns

build:
  type: cmake
  args_if:  # <- note this
    xeno: -DXBOT2_ENABLE_XENO=ON

depends:
  - xbot2
  - cartesian_interface
```

The cmake arg ` -DXBOT2_ENABLE_XENO=ON` is added if calling forest as follows: `forest xbot2_examples -m xeno`. More than one "mode" can be specified at command line.

@MarcoRuzzon what do you think? Can we test it on your use case scenario? Can you think of a better / more flexible way to do this?
